version: "3.9"

services:
  php:
    image: php:8.2-apache
    container_name: php-server
    ports:
      - "8080:80"               # Host port : Container port
    volumes:
      - ./src/php:/var/www/html # Mount your PHP code
    depends_on:
      db:
        condition: service_healthy
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    build: .

  db:
    image: mysql:8.1.0          # Smallest image
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: demo
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8888:80"
    environment:
      PMA_HOST: db
      PMA_USER: appuser
      PMA_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
